language: en
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
  return_sequence: true
- name: RegexFeaturizer
  return_sequence: true
- name: CRFEntityExtractor
  return_sequence: true
- name: EntitySynonymMapper
- name: SklearnIntentClassifier
policies:
- name: FormPolicy
- name: FallbackPolicy
  fallback_action_name: action_default_fallback
- name: MemoizationPolicy
- name: MappingPolicy
- name: KerasPolicy
- name: EmbeddingPolicy
